"""Audit Logger — Tracks AI chat sessions, logic flow, and data usage.

This module helps experts understand how the AI arrives at its answers by logging:
1. The exact user query.
2. The sequence of tools called, including their inputs and the raw data they returned.
3. The final response generated by the AI.
"""

import json
import os
from datetime import datetime
from pathlib import Path

# Create audit logs directory
AUDIT_DIR = Path("audit_logs")
AUDIT_DIR.mkdir(exist_ok=True)


class ChatAuditLogger:
    def __init__(self, session_id: str | None = None):
        self.session_id = session_id or datetime.now().strftime("%Y%md_%H%M%S")
        self.log_file = AUDIT_DIR / f"session_{self.session_id}.jsonl"
        
        self.current_query = ""
        self.flow_steps = []
        self.start_time = datetime.now()

    def start_query(self, query: str):
        """Record the start of a new query."""
        self.current_query = query
        self.flow_steps = []
        self.start_time = datetime.now()

    def log_tool_execution(self, tool_name: str, arguments: dict, result: dict | list | str):
        """Record what tool the AI decided to use and the data it got back."""
        # Truncate very large results to save space, but keep enough for context
        result_str = json.dumps(result, default=str)
        if len(result_str) > 2000:
            result_snippet = result_str[:2000] + "... [TRUNCATED]"
        else:
            result_snippet = result_str

        self.flow_steps.append({
            "step_type": "tool_call",
            "tool_name": tool_name,
            "arguments": arguments,
            "data_returned_snippet": result_snippet,
            "timestamp": datetime.now().isoformat()
        })

    def log_final_response(self, response: str):
        """Record the final answer generated by the AI based on the flow."""
        duration = (datetime.now() - self.start_time).total_seconds()
        
        audit_record = {
            "timestamp": datetime.now().isoformat(),
            "session_id": self.session_id,
            "user_query": self.current_query,
            "logic_flow": self.flow_steps,
            "final_response": response,
            "processing_time_seconds": round(duration, 2)
        }
        
        # Save to JSONL file
        with open(self.log_file, "a", encoding="utf-8") as f:
            f.write(json.dumps(audit_record) + "\n")
            
        # Also create a human-readable markdown summary
        self._write_markdown_summary(audit_record)

    def _write_markdown_summary(self, record: dict):
        """Write a readable markdown version of the session for easy review."""
        md_file = AUDIT_DIR / f"session_{self.session_id}.md"
        
        with open(md_file, "a", encoding="utf-8") as f:
            f.write(f"## Query: {record['user_query']}\n")
            f.write(f"**Time**: {record['timestamp']} | **Duration**: {record['processing_time_seconds']}s\n\n")
            
            f.write("### AI Logic Flow (Tools & Data Used)\n")
            if not record["logic_flow"]:
                f.write("- *No tools used. Answered from internal knowledge.*\n")
            else:
                for i, step in enumerate(record["logic_flow"]):
                    f.write(f"**Step {i+1}: Called `{step['tool_name']}`**\n")
                    f.write(f"- **Arguments**: `{json.dumps(step['arguments'])}`\n")
                    f.write(f"- **Data Received**: {step['data_returned_snippet'][:300]}...\n\n")
            
            f.write("### Final AI Response\n")
            f.write(f"{record['final_response']}\n\n")
            f.write("---\n\n")
